astrac_tagging_patterns:
  register_me:
    -
      register: astrac.tagging_patterns_examples.command_processor
      method: registerProcessor
      tag: astrac.tagging_pattern_examples.command_processor
      parameters: [ key, __service ]
